image: python:3.5

before_script:
  - apt update -qy
  - apt-get install expect
  - pip install --upgrade pip
  - make setup
  - make test_setup

stages:
  - test
  - post-test

style_app:
  type: test
  script:
    - make style

test:
  type: test
  cache:
    paths:
      - tests/test_data/songs
  script:
    - | # Download if needed
      if ! [[ -d tests/test_data/songs ]]; then
          wget https://attach.libremail.nl/songs.tar.gz
          tar xfvz songs.tar.gz
          mv songs/ tests/test_data/
      fi
      mkdir -p coverage
      touch coverage/out
      rm coverage/out
      touch coverage/out
      unbuffer pytest -v --cov-config=.coveragerc --cov-report term-missing --cov=dj_feet --runslow tests/ | awk '{print >>(/^TOTAL/?"coverage/out":"/dev/stdout")}'
  artifacts:
    expire_in: 31d
    paths:
      - coverage/

coverage:
  type: post-test
  script:
    - cat coverage/out
    - cat coverage/out | sed 's/^.* \([^ ]*%\).*/\1/g'
  artifacts:
    name: coverage
    expire_in: 31d
    paths:
    - coverage/index.html
    - coverage/assets/

#old ^TOTAL.*\s+(\d+\%)$
