image: python:3.5

before_script:
  - apt update -qy
  - pip install --upgrade pip
  - make setup

types:
  - test

test_app:
  type: test
  script:
    - wget https://attach.libremail.nl/songs.tar.gz
    - tar xfvz songs.tar.gz
    - mv songs/ test/test_data/
    - make coverage

style_app:
  type: test
  script:
    - make style
