image: python:3.5

before_script:
  - apt update -qy
  - pip install --upgrade pip
  - make setup

types:
  - test

style_app:
  type: test
  script:
    - make style

test_app:
  type: test
  cache:
    paths:
      - test_data/songs
  script:
    - wget https://attach.libremail.nl/songs.tar.gz
    - tar xfvz songs.tar.gz
    - mv songs/ tests/test_data/
    - make coverage
