image: python:3.5

before_script:
  - apt-get update -qy
  - pip install --upgrade pip
  - make setup
  - make test_setup

stages:
  - test
  - post-test

style_app:
  type: test
  script:
    - make style

test:
  type: test
  cache:
    untracked: true
    paths:
      - tests/test_data/songs
  script:
    - | # Download if needed
      [[ -d tests/test_data/songs ]] || wget https://attach.libremail.nl/songs.tar.gz
      [[ -d tests/test_data/songs ]] || tar xfvz songs.tar.gz
      [[ -d tests/test_data/songs ]] || mv songs/ tests/test_data/
      mkdir -p coverage
      touch coverage/out
      rm coverage/out
      touch coverage/out
      pytest -v --durations=30 --cov-config=.coveragerc --cov-report term-missing --cov=dj_feet --runslow tests/ | awk '{print >>(/^TOTAL/?"coverage/out":"/dev/stdout")}'
  artifacts:
    expire_in: 31d
    paths:
      - coverage/

coverage:
  type: post-test
  before_script:
    - echo Nothing necessary
  script:
    - cat coverage/out
    - cat coverage/out | sed 's/^.* \([^ ]*%\).*/\1/g'
  artifacts:
    name: coverage
    expire_in: 31d
    paths:
    - coverage/index.html
    - coverage/assets/
